### ISSUE TITLE
Edits to make based on Milestone 1 feedback

### ISSUE THREAD

**Issue by jbarns14** [UBC-MDS/fifa-potential#36]
- [x] Analysis notebook should be in a logical subfolder
- [x] Edit contributing file. (Either add attribution or use our own words)
- [x] Environment file - make sure versions are there for all packages - Remove environment code from README
- [x] License - add the CC license text 
- [x] Introduction - State classes of potential clearly
- [x] Add legend to the EDA plots
- [ ] Add descriptions to tables
- [x] Link findings back to application domain in discussion

**Comment by srfrew** [comment]
Just a heads up that I'm working on updating the EDA scripts to be black formatting compliant in the `bash-makefile` branch. Once that's merged in can we split off to update EDA plots as recommended in milestone 1? Thoughts?

**Comment by jbarns14** [comment]
Sure that sounds good. Is it not just a matter of updating the eda plot function script to put legends on the plots?

**Comment by srfrew** [comment]
Ah yeah you're right. It doesn't actually need to wait till I finish what I'm doing

**Comment by meretelutz** [comment]
Version tags were added before the milestone 2 submission!

**Comment by jbarns14** [comment]
When it comes to adding descriptions to the plots, that will have to be done once we get the notebook file rendering only the plots we want the reader to see. Is there any chance whoever sets up the notebook rendering can add the plot descriptions? It should only need to be one maybe 2 sentences max just describing the plot.

**Comment by meretelutz** [comment]
The plot actually already has a legend on the side, it must've just been cutoff whenever the grader was looking at the report. Maybe we need to just tweak the sizing of the plots instead so it all fits on a single page

**Comment by srfrew** [comment]
Closing as updates have been merged into main and reference-bibtex and report file
